# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
dist: trusty
sudo: true
cache: packages
warnings_are_errors: false

r:
  - release

r_packages: 
  - covr

r_binary_packages: 
 - rstan
 - rstanarm
 - dplyr
 - igraph
 - RCurl
 - git2r
 - glue
 - magrittr
 - stringi
 - stringr
 - cli
 - crayon
 - pillar
 - scales
 - tibble
 - ggplot2
 - StanHeaders
 - Rcpp

before_install:
  - sudo apt-get -y install libnlopt-dev 
 
after_success:
- Rscript -e 'covr::codecov()'
