language: R
dist: xenial

cache:
  packages: true

env:
  global:
  - MAKEFLAGS="-j 2"

addons:
  apt:
    packages:
    - libnlopt-dev
    - r-cran-rstanarm

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

